# Generated by Django 5.2.12 on 2026-03-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
