# Generated by Django 5.2.12 on 2026-03-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='sub_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
